function isLikelyMathLine(line: string): boolean {
  return /\\[a-zA-Z]+|[_^]|[=<>+\-*/()]/.test(line);
}

function normalizeFractions(input: string): string {
  // Convert simple a/b forms into \frac{a}{b}. Keep this conservative to avoid breaking URLs or paths.
  return input.replace(
    /(^|[\s(（=:+\-*,，。；;])((?:\\[a-zA-Z]+|\d+|[a-zA-Z]))\/((?:\\[a-zA-Z]+|\d+|[a-zA-Z]))(?=$|[\s)）=:+\-*,，。；;])/g,
    (_m, prefix: string, left: string, right: string) => `${prefix}\\frac{${left}}{${right}}`,
  );
}

function normalizeTasksEnvironment(input: string): string {
  return input.replace(
    /(\\begin\{tasks\}(?:\([\d]+\))?)([\s\S]*?)(\\end\{tasks\})/g,
    (_m, start: string, inner: string, end: string) => {
      const fixedInner = inner.replace(/\\item\b/g, '\\task');
      return `${start}\n${fixedInner.trim()}\n${end}`;
    },
  );
}

export function normalizeLatexContent(content: string, type: string = '其他'): string {
  if (!content) return '';
  let fixed = String(content);

  // Remove invisible control chars that often break parsing/rendering.
  fixed = fixed.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F]/g, '');

  // Normalize escaped line-break artifacts from model output.
  fixed = fixed.replace(/\\n/g, '\\\\');

  // Parallel symbol normalization.
  fixed = fixed.replace(/(\s)\/\/(\s)/g, '$1\\mathbin{/\\!/}$2');
  fixed = fixed.replace(/\\parallel\b/g, '\\mathbin{/\\!/}');

  // Remove illegal /b \b style prefixes occasionally generated by OCR/LLM.
  fixed = fixed.replace(/(^|[^a-zA-Z0-9])[\/\\][bt]\s*(?=\\[a-zA-Z]+)/gi, '$1');
  fixed = fixed.replace(/[\/\\][bt]\s*(?=\{)/gi, '');

  // Sub-question and circled-number line split.
  fixed = fixed.replace(/([^\n])\s*(\((?:\d+|[ivxIVX]+)\))/g, '$1\\\\\n$2');
  fixed = fixed.replace(/([^\n])\s*([①②③④⑤⑥⑦⑧⑨⑩])/g, '$1\\\\\n$2');

  fixed = normalizeFractions(fixed);
  fixed = normalizeTasksEnvironment(fixed);

  fixed = fixed.replace(/\\text\{sin\}/g, '\\sin');
  fixed = fixed.replace(/\\text\{cos\}/g, '\\cos');
  fixed = fixed.replace(/\\text\{tan\}/g, '\\tan');
  fixed = fixed.replace(/([^\\a-zA-Z])rac(?=\{)/g, '$1\\frac');

  if (type === '填空题') {
    fixed = fixed.replace(/_{3,}/g, '$\\fillin$');
    fixed = fixed.replace(/（\s*）/g, '$\\fillin$');
    fixed = fixed.replace(/(?<!\$)\\fillin(?!\$)/g, '$\\fillin$');
  }

  // Line-level balancing for odd '$' count.
  fixed = fixed
    .split('\n')
    .map((line) => {
      const dollarCount = (line.match(/\$/g) || []).length;
      if (dollarCount % 2 !== 0 && isLikelyMathLine(line)) {
        return `$${line}$`.replace(/\$\$/g, '$');
      }
      return line;
    })
    .join('\n');

  return fixed.trim();
}
